# Generated by Django 6.0.3 on 2026-04-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('condition_type', models.CharField(max_length=50)),
                ('condition_value', models.IntegerField(default=0)),
                ('game_specific', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'achievements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_achievements',
                'managed': False,
            },
        ),
    ]
