# Generated by Django 6.0.1 on 2026-03-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('show_kids', models.BooleanField(default=False)),
                ('show_teen', models.BooleanField(default=False)),
                ('show_adult', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=6)),
                ('otp_expires', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pending_verifications',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('show_kids', models.BooleanField(default=False)),
                ('show_teen', models.BooleanField(default=False)),
                ('show_adult', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('banned', 'Banned')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
    ]
