# Generated by Django 6.0.3 on 2026-04-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_add_country_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'password_resets',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pendingverification',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False},
        ),
    ]
